1.¿Qué es?


Es un lenguaje de programación gratuito y de código abierto para computación científica, técnica y genérica de alto rendimiento y alto nivel diseñado para realizar análisis numérico. Fue creado en 2009 por Alan Edelman, Stefan Karpinski, Jeff Bezanson y Viral Shah y se ha vuelto popular por su sintaxis expresiva y sus paquetes de Machine Learning de alta velocidad.

2.¿Cómo instalar?

2.1.Instalar para Windows

* paso1: Ir al sitio web de julia "https://julialang.org/downloads/"
* paso2: Instalar la version de julia mas estable (1.10.3v)
* paso3: Ejecute el instalador y elija la carpeta predeterminada o escoja la ruta donde quiere que se instale

2.2.Instalar para Linux

* paso1: Ir al sitio web de julia "https://julialang.org/downloads/"
* paso2: Instalar la version de julia mas estable (1.10.3v)
* paso3: Extrae el archivo descargado con el comando (tar zxvf julia-1.10.3-linux-x86_64.tar.gz)
* paso4: Añada Julia a tu variable de entorno PATH editando el archivo (~/.bashrc) y añadiendo la línea (export PATH="$PATH:/home/tu_usuario/julia-1.10.3/bin")
* paso5: Ejecuta source (~/.bashrc) para que los cambios tengan efecto

2.3.Instalar para MacOs

* paso1: abra la terminal
* paso2: Ejecuta el comando (curl -fsSL https://install.julialang.org | sh)
* paso3: Una vez instalado, Julia estará disponible a través de la interfaz de línea de comandos

Opcional:

si quiere trabajar con Jupyter notebook

* paso1: abra la terminal de julia
* paso2: escriba un "]" para entrar al administrador de paquetes
* paso3: escriba "add IJulia" para instalar el paquete de IJulia "este paquete es para instalar el kernel de julia y poder 
trabajar con jupyter notebook"

3.PAQUETES

En julia es posible aumentar su capacidad utilizando paquetes (ya sea con los que vienen en la instalacion base como con externos).
Los paquetes son invocados (despues de haber sido instalados) usando la sintaxis:

__using nombre_paquete__

Para administrar los paquetes en julia se usa el paquete (pkg). La sintaxis para instalar un paquete es:

* __using Pkg__
* __Pkg.add("nombre_del_paquete")__

Algo importante es que el ordenador debe de estar conectado a internet para descargar los archivos binarios del paquete a instalar. Los
archivos descargados son guardados en la carpeta: ~/.julia/environments/

3.1.Comandos Utiles de Julia

* __Pkg.rm("nombre_del_paquete")__ --> Elimina un paquete
* __Pkg.build("nombre_del_paquete")__ --> Reconstruye un paquete desde sus archivos binarios
* __Pkg.status()__ --> Provee una lista de los paquetes instalados
* __Pkg.update()__ --> Actualiza los paquetes instalados

4.COMENTARIOS  

Comentar o dejar documentación en diferentes partes de un código es muy útil para explicar en detalle que es exactamente qué cálculos se están realizando. Esto es particularmente útil cuando el código es compartido con otra persona o con uno mismo en el futuro.


4.1.Tipos

4.1.1.Comentarios de una sola línea: inician con # 
(Todo lo que precede a este símbolo será parte del comentario.)

In [1]:
#Este es un comentario de una linea en Julia
#Este es otro comentario

4.1.2.Comentarios de bloque: inician con #= y cierran con =#
Estos comentarios son útiles para escribir documentación detallada que requiera de varias líneas.

In [2]:
#= 
    esto
    es un
    coemntario de bloque
 =#

5.VARIABLES

Una variable es un elemento de datos con nombre que puede almacenar diferentes tipos de datos durante la ejecución de un programa. Las variables son fundamentales para el desarrollo de software y la creación de aplicaciones eficientes, ya que permiten a los desarrolladores manipular e interactuar con la información de manera dinámica.

En Julia para declarar variables: nombre_de_la_varaible = valor

El valor asignado corresponde a un tipo de dato

__Importante:__

* Las variables deben tener nombres significativos
* No deben empezar con numeros
* No deben contener caracteres como @
* No pueden ser palabras reservadas

5.1.Tipo de Variables

* 5.1.1.Int (entero)
* 5.1.2.Float (decimal)
* 5.1.3.String (cadena)
* 5.1.4.Char (caracter)
* 5.1.5.Booleano (logico)

5.1.1.Int (entero)

In [10]:
# 64-bit system
numero = 10
typeof(numero)

Int64

5.1.2.Float (decimal)

In [11]:
# 64-bit system
numero = 6.23
typeof(numero)

Float64

5.1.3.String (cadena)

In [4]:
# Cadena de caracteres
nombre = "Luis Carlos"
typeof(nombre)

String

5.1.4.Char (caracter)

In [12]:
# un caracter
character = 'a'
typeof(character)

Char

5.1.5.Booleano (logico)

In [1]:
# una variable logica verdadera
logic1 = true
typeof(logic1)

# una variable logica falsa
logic2 = false
typeof(logic2)

Bool

5.2.Variables Globales

En Julia, las variables globales se definen en el ámbito global y pueden ser accedidas desde cualquier parte del código.

5.2.1.Declaración de variables globales:

 La palabra clave 'global' se utiliza para acceder a una variable desde una función o bloque de código; esta se agrega al principio de la linea de codigo donde se quiere declarar la variable global, y posteriormente se agrega el nombre de la variable, cabe mencionar que el valor de la variable se puede agregar después de la declaración global o cuando se realice la misma.

In [3]:
# DECLARACION DE VARIABLE GLOBAL (Ejemplo)
global varible_global = 56

56

Nota: Las variables globales pueden cambiar de tipo y valor en cualquier momento (debido a que Julia es un lenguaje multihilo). Pero se recomienda utilizar variables locales en lugar de globales para mantener un código más limpio y eficiente, ya que se dificulta el seguimiento del código y puede afectar el rendimiento.


7.Operaciones Matemáticas Basicas
    
    Julia permite hacer las siguientes operaciones:
    7.1.Suma (+)
    7.2.Resta (-)
    7.3.Multiplicación (*)
    7.4.División (/)
    7.5.Potencia (^)
    7.6.Módulo (%)

7.1.Suma (+)

In [4]:
#Variables
x=3 
y=5
#operacion de suma
x+y 
#output : 8

8

7.2.Resta (-)

In [5]:
#Variables
y=5
#operacion de resta
x-y 
#output : -2

-2

7.3.Multiplicación (*)

In [6]:
#Variables
x=3 
y=5
#operacion de multiplicación
x*y 
#output : 15

15

7.4.División (/)

In [7]:
#Variables 
x=25 
y=5
#operacion de división
x/y 
#output : 5.0

5.0

7.5.Potencia (^)

In [8]:
#Variables 
x=3
y=2
#operacion de potencia
x^y 
#output : 9

9

7.6.Módulo (%)

In [9]:
#Variables 
x=3
y=2
#operacion de módulo
x%y #output : 1 

1

8. Condicionales

Los condicionales se utilizan para controlar el flujo del programa, ejecutando bloques de código diferentes según distintas condiciones.

La sintaxis básica para los condicionales en Julia es la siguiente:

    if condicion
        # Bloque de código que se ejecuta si la condición es verdadera
    elseif otra_condicion
        # Bloque de código que se ejecuta si la primera condición es falsa y otra_condicion es verdadera
    else
        # Bloque de código que se ejecuta si ninguna de las condiciones anteriores es verdadera
    end

Ya sabiendo la estructura y como se usan los condicionales. vamos a hablar de los operadores lógicos. Estos operadores son fundamentales porque son los que utilizamos para realizar comparaciones y evaluar las condiciones en nuestros programas.


8. 1 Operadores:


Los operadores lógicos nos permiten establecer reglas más complejas y precisas dentro de los condicionales, ayudándonos a tomar decisiones basadas en múltiples criterios. En Julia, existen varios tipos de operadores lógicos que podemos emplear para este propósito, y a continuación, describiremos los más comunes y su uso.

8. 2 Operadores de comparación

Estos operadores se utilizan para comparar valores numéricos, de texto o de cualquier otro tipo compatible. Los operadores de comparación más comunes son:

In [14]:
# Operador < (menor que): Verifica si el valor a la izquierda es menor que el valor a la derecha
println("3 < 5: ", 3 < 5)  # true

# Operador > (mayor que): Verifica si el valor a la izquierda es mayor que el valor a la derecha
println("5 > 3: ", 5 > 3)  # true

# Operador <= (menor o igual que): Verifica si el valor a la izquierda es menor o igual que el valor a la derecha.
println("3 <= 3: ", 3 <= 3)  # true

# Operador >= (mayor o igual que): Verifica si el valor a la izquierda es mayor o igual que el valor a la derecha.
println("5 >= 3: ", 5 >= 3)  # true

# Operador == (igual a): Verifica si los dos valores son iguales.
println("3 == 3: ", 3 == 3)  # true

# Operador != (no es igual a): Verifica si los dos valores no son iguales
println("3 != 5: ", 3 != 5)  # true

3 < 5: true
5 > 3: true
3 <= 3: true
5 >= 3: true
3 == 3: true
3 != 5: true


8. 3 Operadores Lógicos:

Además de los operadores de comparación, también tenemos operadores lógicos que nos permiten combinar varias condiciones:

In [18]:
# Operador | (OR): Devuelve true si al menos una de las condiciones es verdadera
println("true | false: ", true | false)  # true
println("false | false: ", false | false)  # true

# Operador || (OR corto circuito): Devuelve true si al menos una de las condiciones es verdadera; no evalúa la segunda condición si la primera ya es verdadera.
println("true || false: ", true || false)  # true
println("false || true: ", false || true)  # true

# Operador & (AND): Devuelve true si todas las condiciones son verdaderas
println("true & true: ", true & true)  # true
println("true & false: ", true & false) # false

# Operador && (AND corto circuito): Devuelve true si todas las condiciones son verdaderas; no evalúa la segunda condición si la primera es falsa.
println("true && true: ", true && true)  # true
println("false && true: ", false && true)  # false

# Operador ! (NOT): Invierte el valor de una condición, cambiando true a false y viceversa
println("!true: ", !true)  # false
println("!false: ", !false)  # true

true | false: true
false | false: false
true || false: true
false || true: true
true & true: true
true & false: false
true && true: true
false && true: false
!true: false
!false: true


Ahora que ya vimos como son los operadores y como se utilizan, podemos plantear un ejemplo práctico como puede ser:

In [4]:
# Definimos la variable de edad con la que vamos a trabajar y comparar
edad = 25

# Evaluamos la condición para determinar la categoría de edad y ejecutamos el bloque de código correspondiente

# Si la edad es menor que 13, imprimimos "Niño"
if edad < 13
    println("Niño")
# Si la edad es mayor o igual a 13 y menor o igual a 19, imprimimos "Adolescente"
elseif edad >= 13 && edad <= 19
    println("Adolescente")
# Si la edad es mayor o igual a 20 y menor o igual a 64, imprimimos "Adulto"
elseif edad >= 20 && edad <= 64
    println("Adulto")
# Si ninguna de las condiciones anteriores se cumple, significa que la edad es mayor o igual a 65, por lo tanto, imprimimos "Anciano"
else
    println("Anciano")
end



Adulto


9. Ciclos (Loops)

Los ciclos o Loops son bucles que sirven para realizar operaciones de manera repetida. En Julia existen dos tipos de Loops:

9. 1 Loop for: Realiza la misma acción un número determinado de veces. Su sintaxis es como sigue:

for expresión_iterable

        Comando 1 
        Comando 2
        Comando 3
        ...

    end

Un ejemplo práctico podría ser:

In [23]:
# Inicializamos una variable para almacenar la suma
suma = 0

# Ciclo for que itera sobre un rango de números del 1 al 10, que "i" empieza en 1 y termina en 10
for i in 1:10
    # Añadimos el valor de i a la suma
    suma += i
    # Imprimimos el valor actual de i y la suma parcial
    println("i: ", i, " suma parcial: ", suma)
end

# Imprimimos la suma total después de completar el ciclo
println("La suma total es: ", suma)


i: 1 suma parcial: 1
i: 2 suma parcial: 3
i: 3 suma parcial: 6
i: 4 suma parcial: 10
i: 5 suma parcial: 15
i: 6 suma parcial: 21
i: 7 suma parcial: 28
i: 8 suma parcial: 36
i: 9 suma parcial: 45
i: 10 suma parcial: 55
La suma total es: 55


9. 2 Loop While: Realiza la misma acción hasta que una condición se cumpla. Su sintaxis es como sigue:

while Condición

    Comando 1
    Comando 2
    Comando3
    ...
end

un ejemplo práctico podría ser:

In [27]:
numero_mayor = 5
numero_menor = 1

# Iniciamos un ciclo while que se ejecutará mientras numero_mayor sea mayor que numero_menor
while numero_mayor > numero_menor
    # Imprimimos el valor actual del numero menor
    println("El número es: ", numero_menor)
    
    # Incrementamos el valor de numero_menor en 1
    numero_menor += 1
end

El número es: 1
El número es: 2
El número es: 3
El número es: 4


10. Arrays
Los arrays son un tipo de estructura que contiene datos relacionados, con ellos pueden ser representados vectores y matrices.

En Julia los Arrays son listas, que pueden contener más de un tipo de dato, según este sea creado o inicializado, además implementa métodos para incrementar y eliminar elementos. También, a diferencia de otras estructuras los array pueden tener datos duplicados.

10. 1  Inicialización de un array

El array puede ser inicializado de diversas maneras, las cuales son:

- Usando el constructor explícito

In [29]:
array₁ = Array{Float64}(undef,5,2,2)

5×2×2 Array{Float64, 3}:
[:, :, 1] =
 7.40745e-312  7.40745e-312
 7.40745e-312  7.40745e-312
 7.40745e-312  7.40745e-312
 7.40758e-312  7.40745e-312
 7.40745e-312  7.40745e-312

[:, :, 2] =
 7.40745e-312  7.40745e-312
 7.40745e-312  7.40745e-312
 7.40745e-312  7.40745e-312
 7.40745e-312  7.40745e-312
 7.40745e-312  7.40758e-312

- Array literal

Se puede crear un array utilizando corchetes [] y separando los elementos por comas.

In [31]:
# Crear un array de enteros
array_enteros = [1, 2, 3, 4, 5]

# Crear un array de cadenas de texto
array_cadenas = ["hola", "mundo"]


2-element Vector{String}:
 "hola"
 "mundo"

- Array Vacio

Se puede crear un array vacío y especificar su tipo.

In [33]:
# Crear un array vacío de enteros
array_vacio = Int64[]


Int64[]

- Array con Valores Repetidos:

Puedes crear un array con un valor repetido un cierto número de veces usando la función fill.

In [34]:
# Crear un array de tamaño 5, con todos los elementos igual a 0
array_repetidos = fill(0, 5)


5-element Vector{Int64}:
 0
 0
 0
 0
 0

- Array con un rango:

Se puede crear un array que contenga un rango de números.

In [35]:
# Crear un array con números del 1 al 10
array_rango = collect(1:10)


10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

- Array de ceros:
Un array de ceros puede ser creado con el método zeros, que admite como argumentos el tipo de datos y luego las dimensiones del array.

In [37]:
array_zeros = zeros(Int64,4)
matriz_zeros = zeros(Float64,4,4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

10. 2  Acceder a los elementos de un array
Se accede a los elementos de un array con [] e indicando la posición de elemento

In [38]:
# Crear un array de enteros
array_enteros = [10, 20, 30, 40, 50]

# Acceder y mostrar el primer elemento del array
primer_elemento = array_enteros[1]
println("El primer elemento es: ", primer_elemento)  # 10

El primer elemento es: 10


Como puede ser observado, a diferencia de otros lenguajes de programación, Julia tiene indexación base-1, lo que significa que para el primer elemento del array tiene índice 1 no 0.

In [39]:
# Crear un array de enteros
array_enteros = [10, 20, 30, 40, 50]

# Acceder y mostrar el tercer elemento del array
tercer_elemento = array_enteros[3]
println("El tercer elemento es: ", tercer_elemento)  # 30

# Acceder y mostrar el último elemento del array
ultimo_elemento = array_enteros[end]
println("El último elemento es: ", ultimo_elemento)  # 50

# Acceder y mostrar los elementos en un rango de índices (del segundo al cuarto)
rango_elementos = array_enteros[2:4]
println("Los elementos del segundo al cuarto son: ", rango_elementos)  # [20, 30, 40]

# Acceder y mostrar elementos usando un array de índices específicos
indices_especificos = [1, 3, 5]
elementos_especificos = array_enteros[indices_especificos]
println("Los elementos en los índices 1, 3 y 5 son: ", elementos_especificos)  # [10, 30, 50]


El tercer elemento es: 30
El último elemento es: 50
Los elementos del segundo al cuarto son: [20, 30, 40]
Los elementos en los índices 1, 3 y 5 son: [10, 30, 50]


Otros ejemplos de como acceder a los elementos de un array pueden ser:

In [40]:
array3dim = cat([1 2; 3 4],["Hola 1" "Hola 2"; "Hola 3" "Hola 4"],[5 6; 7 8],dims=3)

array3dim[1,1,2] # Hola 1

"Hola 1"

En este ejemplo se puede apreciar como accedemos a un elmento de un array de 3 dimensiones, basicamente indicando la posición con una terna de numeros. Aunque se puede acceder a más de un elemento extrayendo un subarray del primero:

In [46]:
array3dim = cat([1 2; 3 4],["Hola 1" "Hola 2"; "Hola 3" "Hola 4"],[5 6; 7 8],dims=3)

array3dim[:,:,2]

2×2 Matrix{Any}:
 "Hola 1"  "Hola 2"
 "Hola 3"  "Hola 4"

11.TUPLAS

Una tupla es una colección ordenada de tamaño fijo que puede contener elementos de distintos tipos.
Generalmente se usan para pasar parámetros o devolver valores de funciones.
Se crean escribiendo sus elementos separados por comas entre paréntesis.

__ADVERTENCIA__: Las tuplas son inmutables, es decir, una vez creadas no pueden cambiarse sus elementos.

Las tuplas se crean usando las siguiente sintaxis: nombre = (itemq, item2, ....)

In [13]:
# Tupla vacia
tp_vacia = ()
println(tp_vacia)

# tupla con distintos tipos de variables
tp = (10,"Marzo",200.23)
println(tp)

typeof(tp_vacia)
typeof(tp)

()
(10, "Marzo", 200.23)


Tuple{Int64, String, Float64}

11.1.Tuplas con Nombres

Es posible asignar un nombre a cada uno de los elementos de la tupla. Para ello cada elemento de la tupla con nombre debe escribirse con la sintaxis: <br>
__nombre = valor__

In [16]:
tp = (pais = "Venezuela", estado = "Carabobo", ciudad = "Valencia")
println(tp)
typeof(tp)

(pais = "Venezuela", estado = "Carabobo", ciudad = "Valencia")


@NamedTuple{pais::String, estado::String, ciudad::String}

__ADVERTENCIA__: No puede haber dos elementos con el mismo nombre en una tupla.
<br><br>
La ventaja de usar tuplas con nombres es que podemos acceder a sus elementos por nombre, además de por índice.

11.2.Acesso de Elementos de una Tupla

Como las tuplas tienen orden, podemos acceder a sus elementos mediante índices, al igual que con los arrays de una dimensión.

* __t[i]__: Devuelve el elemento con íncide __i__ de la tupla __t__. <br>
Si la tupla tiene nombres también es posible acceder a sus elementos mediante los nombres.
* __t.x__: Devuelve el elemento con nombre __x__ de la tupla __t__.

In [17]:
tp = (pais = "Venezuela", estado = "Carabobo", ciudad = "Valencia")

println(tp[3]) # Valencia
println(tp.pais) # Venezuela

Valencia
Venezuela


11.3.Asignacion Multiple de tuplas

Es posible asignar los elementos de una tupla a distintas variables en una sola asignación.
<br><br>
__x, y, ... = t__: Asigna a las variables __x, y__, etc los elementos de la tupla __t__ en orden. Si el número de variables es menor que el tamaño de la tupla, los últimos elementos quedan sin asignar.

__x, y... = t__: Asigna el primer elemento de la tupla __t__ a la variable __x__ y la tupla con los elementos restantes a la variable __y__.

In [19]:
tp = ("Juan", 2024, 'h', 12.3)

# asignamos cuatro variables a la tupla tp
n, a, c, d = tp

println(n)
println(a)
println(c)
println(d)

# asignamos 2 variables a la tupla tp
n, acd... = tp

println(n)
println(acd)


Juan
2024
h
12.3
Juan
(2024, 'h', 12.3)
