
# JULIA DOCUMENTANCIÓN
<br>
Elaborado por: Jesús Araujo, Lai Chang y Santiago Perrotta.

#### __1. ¿Qué es?__

Es un lenguaje de programación gratuito y de código abierto para computación científica, técnica y genérica de alto rendimiento y alto nivel diseñado para realizar análisis numérico. Fue creado en 2009 por Alan Edelman, Stefan Karpinski, Jeff Bezanson y Viral Shah y se ha vuelto popular por su sintaxis expresiva y sus paquetes de Machine Learning de alta velocidad.

#### __2. ¿Cómo instalar?__

__2.1. Instalar para Windows__

* paso 1: Ir al sitio web de julia "https://julialang.org/downloads/"
* paso 2: Instalar la version de julia mas estable (1.10.3v)
* paso 3: Ejecute el instalador y elija la carpeta predeterminada o escoja la ruta donde quiere que se instale

__2.2. Instalar para Linux__

* paso 1: Ir al sitio web de julia "https://julialang.org/downloads/"
* paso 2: Instalar la version de julia mas estable (1.10.3v)
* paso 3: Extrae el archivo descargado con el comando (tar zxvf julia-1.10.3-linux-x86_64.tar.gz)
* paso 4: Añada Julia a tu variable de entorno PATH editando el archivo (~/.bashrc) y añadiendo la línea (export PATH="$PATH:/home/tu_usuario/julia-1.10.3/bin")
* paso 5: Ejecuta source (~/.bashrc) para que los cambios tengan efecto

__2.3. Instalar para MacOs__

* paso 1: abra la terminal
* paso 2: Ejecuta el comando (curl -fsSL https://install.julialang.org | sh)
* paso 3: Una vez instalado, Julia estará disponible a través de la interfaz de línea de comandos

__Opcional__

si quiere trabajar con __Jupyter notebook__

* paso 1: abra la terminal de julia
* paso 2: escriba un "]" para entrar al administrador de paquetes
* paso 3: escriba "add IJulia" para instalar el paquete de IJulia "este paquete es para instalar el kernel de julia y poder trabajar con jupyter notebook"

#### __3. Paquetes__

En julia es posible aumentar su capacidad utilizando paquetes (ya sea con los que vienen en la instalacion base como con externos).
Los paquetes son invocados (despues de haber sido instalados) usando la sintaxis:

__using nombre_paquete__

Para administrar los paquetes en julia se usa el paquete (pkg). La sintaxis para instalar un paquete es:

* __using Pkg__
* __Pkg.add("nombre_del_paquete")__

Algo importante es que el ordenador debe de estar conectado a internet para descargar los archivos binarios del paquete a instalar. Los
archivos descargados son guardados en la carpeta: ~/.julia/environments/

__3.1. Comandos Utiles de Julia__

* __Pkg.rm("nombre_del_paquete")__ --> Elimina un paquete
* __Pkg.build("nombre_del_paquete")__ --> Reconstruye un paquete desde sus archivos binarios
* __Pkg.status()__ --> Provee una lista de los paquetes instalados
* __Pkg.update()__ --> Actualiza los paquetes instalados

#### __4. Comentarios__  

Comentar o dejar documentación en diferentes partes de un código es muy útil para explicar en detalle que es exactamente qué cálculos se están realizando. Esto es particularmente útil cuando el código es compartido con otra persona o con uno mismo en el futuro.


__4.1. Tipos__

* __4.1.1.Comentarios de una sola línea__: inician con # 
(Todo lo que precede a este símbolo será parte del comentario.)

In [41]:
#Este es un comentario de una linea en Julia
#Este es otro comentario

* __4.1.2. Comentarios de bloque__: inician con #= y cierran con =#
Estos comentarios son útiles para escribir documentación detallada que requiera de varias líneas.

In [42]:
#= 
    esto
    es un
    coemntario de bloque
 =#


#### __5. Variables__

Una variable es un elemento de datos con nombre que puede almacenar diferentes tipos de datos durante la ejecución de un programa. Las variables son fundamentales para el desarrollo de software y la creación de aplicaciones eficientes, ya que permiten a los desarrolladores manipular e interactuar con la información de manera dinámica.

En Julia para declarar variables: __nombre_de_la_varaible = valor__

El valor asignado corresponde a un tipo de dato

__Importante:__

* Las variables deben tener nombres significativos
* No deben empezar con numeros
* No deben contener caracteres como @
* No pueden ser palabras reservadas

__5.1. Tipos de Variables__

* 5.1.1.Int (entero)
* 5.1.2.Float (decimal)
* 5.1.3.String (cadena)
* 5.1.4.Char (caracter)
* 5.1.5.Booleano (logico)

__5.1.1. Int (entero)__

In [43]:
# 64-bit system
numero = 10
typeof(numero)

Int64

__5.1.2. Float (decimal)__

In [44]:
# 64-bit system
numero = 6.23
typeof(numero)

Float64

__5.1.3. String (cadena)__

In [45]:
# Cadena de caracteres
nombre = "Luis Carlos"
typeof(nombre)

String

__5.1.4. Char (caracter)__

In [46]:
# un caracter
character = 'a'
typeof(character)

Char

__5.1.5. Booleano (logico)__

In [47]:
# una variable logica verdadera
logic1 = true
typeof(logic1)

# una variable logica falsa
logic2 = false
typeof(logic2)

Bool


__5.2. Variables Globales__

En Julia, las variables globales se definen en el ámbito global y pueden ser accedidas desde cualquier parte del código.

__5.2.1. Declaración de variables globales:__

 La palabra clave '__global__' se utiliza para acceder a una variable desde una función o bloque de código; esta se agrega al principio de la linea de codigo donde se quiere declarar la variable global, y posteriormente se agrega el nombre de la variable, cabe mencionar que el valor de la variable se puede agregar después de la declaración global o cuando se realice la misma.

In [48]:
# DECLARACION DE VARIABLE GLOBAL (Ejemplo)
global varible_global = 56

56

__Nota__: Las variables globales pueden cambiar de tipo y valor en cualquier momento (debido a que Julia es un lenguaje multihilo). Pero se recomienda utilizar variables locales en lugar de globales para mantener un código más limpio y eficiente, ya que se dificulta el seguimiento del código y puede afectar el rendimiento.


__6. Operaciones Matemáticas Basicas__
    
Julia permite hacer las siguientes operaciones:
* 6.1. Suma (+)
* 6.2. Resta (-)
* 6.3. Multiplicación (*)
* 6.4. División (/)
* 6.5. Potencia (^)
* 6.6. Módulo (%)

__6.1. Suma (+)__

In [49]:
#Variables
x=3 
y=5
#operacion de suma
x+y 

8

__6.2. Resta (-)__

In [50]:
#Variables
y=5
#operacion de resta
x-y 

-2

__6.3. Multiplicación (*)__

In [51]:
#Variables
x=3 
y=5
#operacion de multiplicación
x*y 

15

__6.4. División (/)__

In [52]:
#Variables 
x=25 
y=5
#operacion de división
x/y 

5.0

__6.5. Potencia (^)__

In [53]:
#Variables 
x=3
y=2
#operacion de potencia
x^y 

9

__6.6. Módulo (%)__

In [54]:
#Variables 
x=3
y=2
#operacion de módulo
x%y 

1

#### __7. Condicionales__

Los condicionales se utilizan para controlar el flujo del programa, ejecutando bloques de código diferentes según distintas condiciones.

La sintaxis básica para los condicionales en Julia es la siguiente:

    if condicion
        # Bloque de código que se ejecuta si la condición es verdadera
    elseif otra_condicion
        # Bloque de código que se ejecuta si la primera condición es falsa y otra_condicion es verdadera
    else
        # Bloque de código que se ejecuta si ninguna de las condiciones anteriores es verdadera
    end

Ya sabiendo la estructura y como se usan los condicionales. vamos a hablar de los operadores lógicos. Estos operadores son fundamentales porque son los que utilizamos para realizar comparaciones y evaluar las condiciones en nuestros programas.


__7. 1 Operadores__


Los operadores lógicos nos permiten establecer reglas más complejas y precisas dentro de los condicionales, ayudándonos a tomar decisiones basadas en múltiples criterios. En Julia, existen varios tipos de operadores lógicos que podemos emplear para este propósito, y a continuación, describiremos los más comunes y su uso.

__7. 2 Operadores de comparación__

Estos operadores se utilizan para comparar valores numéricos, de texto o de cualquier otro tipo compatible. Los operadores de comparación más comunes son:

In [55]:
# Operador < (menor que): Verifica si el valor a la izquierda es menor que el valor a la derecha
println("3 < 5: ", 3 < 5)  # true

# Operador > (mayor que): Verifica si el valor a la izquierda es mayor que el valor a la derecha
println("5 > 3: ", 5 > 3)  # true

# Operador <= (menor o igual que): Verifica si el valor a la izquierda es menor o igual que el valor a la derecha.
println("3 <= 3: ", 3 <= 3)  # true

# Operador >= (mayor o igual que): Verifica si el valor a la izquierda es mayor o igual que el valor a la derecha.
println("5 >= 3: ", 5 >= 3)  # true

# Operador == (igual a): Verifica si los dos valores son iguales.
println("3 == 3: ", 3 == 3)  # true

# Operador != (no es igual a): Verifica si los dos valores no son iguales
println("3 != 5: ", 3 != 5)  # true

3 < 5: true
5 > 3: true
3 <= 3: true
5 >= 3: true
3 == 3: true
3 != 5: true


__7. 3 Operadores Lógicos__

Además de los operadores de comparación, también tenemos operadores lógicos que nos permiten combinar varias condiciones:

In [56]:
# Operador | (OR): Devuelve true si al menos una de las condiciones es verdadera
println("true | false: ", true | false)  # true
println("false | false: ", false | false)  # true

# Operador || (OR corto circuito): Devuelve true si al menos una de las condiciones es verdadera; no evalúa la segunda condición si la primera ya es verdadera.
println("true || false: ", true || false)  # true
println("false || true: ", false || true)  # true

# Operador & (AND): Devuelve true si todas las condiciones son verdaderas
println("true & true: ", true & true)  # true
println("true & false: ", true & false) # false

# Operador && (AND corto circuito): Devuelve true si todas las condiciones son verdaderas; no evalúa la segunda condición si la primera es falsa.
println("true && true: ", true && true)  # true
println("false && true: ", false && true)  # false

# Operador ! (NOT): Invierte el valor de una condición, cambiando true a false y viceversa
println("!true: ", !true)  # false
println("!false: ", !false)  # true

true | false: true
false | false: false
true || false: true
false || true: true
true & true: true
true & false: false
true && true: true
false && true: false
!true: false
!false: true


Ahora que ya vimos como son los operadores y como se utilizan, podemos plantear un ejemplo práctico como puede ser:

In [57]:
# Definimos la variable de edad con la que vamos a trabajar y comparar
edad = 25

# Evaluamos la condición para determinar la categoría de edad y ejecutamos el bloque de código correspondiente

# Si la edad es menor que 13, imprimimos "Niño"
if edad < 13
    println("Niño")
# Si la edad es mayor o igual a 13 y menor o igual a 19, imprimimos "Adolescente"
elseif edad >= 13 && edad <= 19
    println("Adolescente")
# Si la edad es mayor o igual a 20 y menor o igual a 64, imprimimos "Adulto"
elseif edad >= 20 && edad <= 64
    println("Adulto")
# Si ninguna de las condiciones anteriores se cumple, significa que la edad es mayor o igual a 65, por lo tanto, imprimimos "Anciano"
else
    println("Anciano")
end



Adulto


#### __8. Ciclos (Loops)__

Los ciclos o Loops son bucles que sirven para realizar operaciones de manera repetida. En Julia existen dos tipos de Loops:

* __8.1. Loop for__: Realiza la misma acción un número determinado de veces. Su sintaxis es como sigue:

for expresión_iterable

        Comando 1 
        Comando 2
        Comando 3
        ...

    end

Un ejemplo práctico podría ser:

In [58]:
# Inicializamos una variable para almacenar la suma
suma = 0

# Ciclo for que itera sobre un rango de números del 1 al 10, que "i" empieza en 1 y termina en 10
for i in 1:10
    # Añadimos el valor de i a la suma
    suma += i
    # Imprimimos el valor actual de i y la suma parcial
    println("i: ", i, " suma parcial: ", suma)
end

# Imprimimos la suma total después de completar el ciclo
println("La suma total es: ", suma)


i: 1 suma parcial: 1
i: 2 suma parcial: 3
i: 3 suma parcial: 6
i: 4 suma parcial: 10
i: 5 suma parcial: 15
i: 6 suma parcial: 21
i: 7 suma parcial: 28
i: 8 suma parcial: 36
i: 9 suma parcial: 45
i: 10 suma parcial: 55
La suma total es: 55


__8. 2 Loop While__: Realiza la misma acción hasta que una condición se cumpla. Su sintaxis es como sigue:

while Condición

    Comando 1
    Comando 2
    Comando3
    ...
end

un ejemplo práctico podría ser:

In [59]:
numero_mayor = 5
numero_menor = 1

# Iniciamos un ciclo while que se ejecutará mientras numero_mayor sea mayor que numero_menor
while numero_mayor > numero_menor
    # Imprimimos el valor actual del numero menor
    println("El número es: ", numero_menor)
    
    # Incrementamos el valor de numero_menor en 1
    numero_menor += 1
end

El número es: 1
El número es: 2
El número es: 3
El número es: 4


#### __9. Arrays__
Los arrays son un tipo de estructura que contiene datos relacionados, con ellos pueden ser representados vectores y matrices.

En Julia los Arrays son listas, que pueden contener más de un tipo de dato, según este sea creado o inicializado, además implementa métodos para incrementar y eliminar elementos. También, a diferencia de otras estructuras los array pueden tener datos duplicados.

__9. 1  Inicialización de un array__

El array puede ser inicializado de diversas maneras, las cuales son:

* __Usando el constructor explícito__

In [60]:
array₁ = Array{Float64}(undef,5,2,2)

5×2×2 Array{Float64, 3}:
[:, :, 1] =
 8.89767e-315  1.19997e-315
 1.19997e-315  1.19997e-315
 1.19997e-315  8.89767e-315
 1.19997e-315  1.19997e-315
 1.19997e-315  1.19997e-315

[:, :, 2] =
 1.19997e-315  1.19997e-315
 1.19997e-315  1.19997e-315
 1.19997e-315  1.19997e-315
 1.19997e-315  1.19997e-315
 1.19997e-315  0.0

* __Array literal__

Se puede crear un array utilizando corchetes [] y separando los elementos por comas.

In [61]:
# Crear un array de enteros
array_enteros = [1, 2, 3, 4, 5]

# Crear un array de cadenas de texto
array_cadenas = ["hola", "mundo"]


2-element Vector{String}:
 "hola"
 "mundo"

* __Array Vacio__

Se puede crear un array vacío y especificar su tipo.

In [62]:
# Crear un array vacío de enteros
array_vacio = Int64[]


Int64[]

* __Array con Valores Repetidos__

Puedes crear un array con un valor repetido un cierto número de veces usando la función fill.

In [63]:
# Crear un array de tamaño 5, con todos los elementos igual a 0
array_repetidos = fill(0, 5)


5-element Vector{Int64}:
 0
 0
 0
 0
 0

* __Array con un rango__

Se puede crear un array que contenga un rango de números.

In [64]:
# Crear un array con números del 1 al 10
array_rango = collect(1:10)


10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

* __Array de ceros__
Un array de ceros puede ser creado con el método zeros, que admite como argumentos el tipo de datos y luego las dimensiones del array.

In [65]:
array_zeros = zeros(Int64,4)
matriz_zeros = zeros(Float64,4,4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

__9.2.  Acceder a los elementos de un array__

Se accede a los elementos de un array con [] e indicando la posición de elemento

In [66]:
# Crear un array de enteros
array_enteros = [10, 20, 30, 40, 50]

# Acceder y mostrar el primer elemento del array
primer_elemento = array_enteros[1]
println("El primer elemento es: ", primer_elemento)  # 10

El primer elemento es: 10


Como puede ser observado, a diferencia de otros lenguajes de programación, Julia tiene indexación base-1, lo que significa que para el primer elemento del array tiene índice 1 no 0.

In [67]:
# Crear un array de enteros
array_enteros = [10, 20, 30, 40, 50]

# Acceder y mostrar el tercer elemento del array
tercer_elemento = array_enteros[3]
println("El tercer elemento es: ", tercer_elemento)  # 30

# Acceder y mostrar el último elemento del array
ultimo_elemento = array_enteros[end]
println("El último elemento es: ", ultimo_elemento)  # 50

# Acceder y mostrar los elementos en un rango de índices (del segundo al cuarto)
rango_elementos = array_enteros[2:4]
println("Los elementos del segundo al cuarto son: ", rango_elementos)  # [20, 30, 40]

# Acceder y mostrar elementos usando un array de índices específicos
indices_especificos = [1, 3, 5]
elementos_especificos = array_enteros[indices_especificos]
println("Los elementos en los índices 1, 3 y 5 son: ", elementos_especificos)  # [10, 30, 50]


El tercer elemento es: 30
El último elemento es: 50
Los elementos del segundo al cuarto son: [20

, 30, 40]
Los elementos en los índices 1, 3 y 5 son: [10, 30, 50]


Otros ejemplos de como acceder a los elementos de un array pueden ser:

In [68]:
array3dim = cat([1 2; 3 4],["Hola 1" "Hola 2"; "Hola 3" "Hola 4"],[5 6; 7 8],dims=3)

array3dim[1,1,2] # Hola 1

"Hola 1"

En este ejemplo se puede apreciar como accedemos a un elmento de un array de 3 dimensiones, basicamente indicando la posición con una terna de numeros. Aunque se puede acceder a más de un elemento extrayendo un subarray del primero:

In [69]:
array3dim = cat([1 2; 3 4],["Hola 1" "Hola 2"; "Hola 3" "Hola 4"],[5 6; 7 8],dims=3)

array3dim[:,:,2]

2×2 Matrix{Any}:
 "Hola 1"  "Hola 2"
 "Hola 3"  "Hola 4"

#### __10. Tuplas__

Una tupla es una colección ordenada de tamaño fijo que puede contener elementos de distintos tipos.
Generalmente se usan para pasar parámetros o devolver valores de funciones.
Se crean escribiendo sus elementos separados por comas entre paréntesis.

__ADVERTENCIA__: Las tuplas son inmutables, es decir, una vez creadas no pueden cambiarse sus elementos.

Las tuplas se crean usando las siguiente sintaxis: __nombre = (itemq, item2, ....)__

In [70]:
# Tupla vacia
tp_vacia = ()
println(tp_vacia)

# tupla con distintos tipos de variables
tp = (10,"Marzo",200.23)
println(tp)

typeof(tp_vacia)
typeof(tp)

()
(10, "Marzo", 200.23)


Tuple{Int64, String, Float64}

__10.1.Tuplas con Nombres__

Es posible asignar un nombre a cada uno de los elementos de la tupla. Para ello cada elemento de la tupla con nombre debe escribirse con la sintaxis: <br>

__nombre = valor__

In [71]:
tp = (pais = "Venezuela", estado = "Carabobo", ciudad = "Valencia")
println(tp)
typeof(tp)

(pais = "Venezuela", estado = "Carabobo", ciudad = "Valencia")


NamedTuple{(:pais, :estado, :ciudad), Tuple{String, String, String}}

__ADVERTENCIA__: No puede haber dos elementos con el mismo nombre en una tupla.
<br><br>
La ventaja de usar tuplas con nombres es que podemos acceder a sus elementos por nombre, además de por índice.

__10.2. Acesso de Elementos de una Tupla__

Como las tuplas tienen orden, podemos acceder a sus elementos mediante índices, al igual que con los arrays de una dimensión.

* __t[i]__: Devuelve el elemento con íncide __i__ de la tupla __t__. <br>
Si la tupla tiene nombres también es posible acceder a sus elementos mediante los nombres.
* __t.x__: Devuelve el elemento con nombre __x__ de la tupla __t__.

In [72]:
tp = (pais = "Venezuela", estado = "Carabobo", ciudad = "Valencia")

println(tp[3]) # Valencia
println(tp.pais) # Venezuela

Valencia
Venezuela


__10.3. Asignacion Multiple de tuplas__

Es posible asignar los elementos de una tupla a distintas variables en una sola asignación.
<br><br>
__x, y, ... = t__: Asigna a las variables __x, y__, etc los elementos de la tupla __t__ en orden. Si el número de variables es menor que el tamaño de la tupla, los últimos elementos quedan sin asignar.

__x, y... = t__: Asigna el primer elemento de la tupla __t__ a la variable __x__ y la tupla con los elementos restantes a la variable __y__.

In [73]:
tp = ("Juan", 2024, 'h', 12.3)

# asignamos cuatro variables a la tupla tp
n, a, c, d = tp

println(n)
println(a)
println(c)
println(d)

# asignamos 2 variables a la tupla tp
n, acd... = tp

println(n)
println(acd)


Juan
2024
h
12.3
Juan
(2024, 'h', 12.3)


#### __11. DICCIONARIOS__

Un diccionario es una colección asociativa sin orden cuyos elementos son pares formados por una clave y un valor asociado a la clave.
Se parecen a las tuplas con nombre, pero, a diferencia de estas, son mutables, es decir, su contenido se puede alterar.
<br><br>
__Dict(k1 => v1, ...)__: Crea un diccionario con los pares indicados en formato clave => valor

__ADVERTENCIA__: En un diccionario no pueden existir dos pares con la misma clave, de modo que si se repite una clave se sobrescribe el par anterior.

Ejemplos de Diccionarios

In [74]:
# Diccionario vacio
d_vacio = Dict()
println(d_vacio)

d = Dict("cedula1" => "30345678", "cedula2" => "28098321", "cedula3" => "11567987")
println(d)

typeof(d)

Dict{Any, Any}()
Dict("cedula1" => "30345678", "cedula2" => "28098321", "cedula3" => "11567987")


Dict{String, String}

__11.1. Acceso a los elementos de un Diccionario__

Para acceder a los valores de un diccionario se utilizan sus claves asociadas entre corchetes. <br>
__d[k]__: Devuelve el valor asociado a la clave __k__ en el diccionario __d__.

__ADVERTENCIA__: Si la clave no existe en el diccionario se produce un error. <br><br>

Para evitar errores es conveniente usar algunas de las siguientes funciones: 

* __haskey(d,k)__: Devuelve true si la clave __k__ está en diccionario __d__ y false en caso contrario.
* __get(d, k, v)__: Devuelve el valor asociado a la clave __k__ en el diccionario __d__ o el valor __v__ si la clave __k__ no existe.
* __get!(d, k, v)__: Devuelve el valor asociado a la clave __k__ en el diccionario __d__. Si la clave __k__ no existe en el <br> diccionario __d__ añade el par con la clave __k__ y el valor __v__ y devuelve el valor __v__.

Ejemplo de acceso a los elementos de un diccionario:

In [75]:
d = Dict("cedula1" => "30345678", "cedula2" => "28098321", "cedula3" => "11567987")
println(d)

println(d["cedula2"])  # "28098321"

#=
println(d["cedula10"]) # no existe esta clave

como esa clave no existe el interprete va arrojar un error

KeyError: key "cedula10" not found

Stacktrace:
 [1] getindex(h::Dict{String, String}, key::String)
   @ Base .\dict.jl:498
 [2] top-level scope
   @ In[25]:6

=#

# get(d,k,v)
println(get(d,"cedula10","11567987")) # como la clave k no existe, se va a tomar en cuenta el valor de v

# get!(d,k,v)
println(get!(d,"cedula10","30345678")) # como la clave k no existe, se añade el par con la clave k y el valor de v, y se devuelve el valor de v

println(d)

Dict("cedula1" => "30345678", "cedula2" => "28098321", "cedula3" => "11567987")
28098321
11567987
30345678
Dict("cedula1" => "30345678", "cedula2" => "28098321", "cedula3" => "11567987", "cedula10" => "30345678")


__11.2. Recorrido de las claves y valores de un diccionario__

Las siguientes funciones permiten obtener todas las claves, valores y pares de un diccionario.

* __keys(d)__: Devuelve un iterador con las claves del diccionario d.
* __values(d)__: Devuelve un iterador con los valores del diccionario d.
<br>

Estos iteradores permiten recorrer fácilmente los pares de un diccionario.

In [76]:
d = Dict("cedula1" => "30345678", "cedula2" => "28098321", "cedula3" => "11567987")

println(keys(d))
println(values(d))

keys(d)
values(d)

println("")

# ciclo for para recorrer las claves del diccionario

for k = keys(d)
    println("$k = $(d[k])")
end

println("")
# ciclo for para recorrer clave, valor del diccionario

for (k, v) = d
    println("$k = $v")
end

["cedula1", "cedula2", "cedula3"]
["30345678", "28098321", "11567987"]

cedula1 = 30345678
cedula2 = 28098321
cedula3 = 11567987

cedula1 = 30345678
cedula2 = 28098321
cedula3 = 11567987


__11.3. Añadir elementos a un diccionario__

* __d[k] = v__: Añade el par con clave __k__ y valor __v__ al diccionario __d__. Si la clave __k__ ya existía en el diccionario __d__, cambia su valor asociado por __v__.

In [77]:
d = Dict("cedula1" => "30345678", "cedula2" => "28098321", "cedula3" => "11567987")

d["cedula4"] = "15650812" # este va agregar un par de clave, valor
d["cedula1"] = "33001900" # este va a modificar el valor que se encuentra en la clave "cedula1"

println(d)

Dict("cedula4" => "15650812", "cedula1" => "33001900", "cedula2" => "28098321", "cedula3" => "11567987")


__11.4. Eliminar elementos de un diccionario__

* __delete!(d, k)__: Elimina el par cuya clave es __k__ del diccionario __d__.

In [78]:
d = Dict("cedula1" => "30345678", "cedula2" => "28098321", "cedula3" => "11567987")

delete!(d,"cedula2") # elimina del diccionario el par asociado a la clave que se le pasa como argumento a delete

println(d)

Dict("cedula1" => "30345678", "cedula3" => "11567987")


####  __12. Excepciones__

Julia permite el manejo de excepciones mediante el uso de un bloque try-catch. El bloque de código que posiblemente puede generar una excepción se coloca en el bloque try y el bloque catch maneja la excepción generada. La excepción se propaga a través de la pila de llamadas hasta que se encuentra un bloque try-catch

In [79]:
# Imprimir un mensaje antes de la excepción
println("Antes de la Excepción")

# Intentar calcular la raíz cuadrada de un número negativo
try
    sqrt(-1)  # Esto lanzará una excepción porque no se puede calcular la raíz cuadrada de un número negativo
catch
    # Capturar la excepción y manejarla imprimiendo un mensaje
    println("No se puede encontrar la raíz cuadrada de números negativos")
end

# Imprimir un mensaje después de manejar la excepción
println("Después de la Excepción")


Antes de la Excepción
No se puede encontrar la raíz cuadrada de números negativos
Después de la Excepción



El código intenta calcular la raíz cuadrada de un número negativo (sqrt(-1)), lo cual lanza una excepción porque no es posible para números reales. Antes de este intento, imprime "Antes de la Excepción". Al producirse la excepción, es capturada por el bloque catch, que imprime "No se puede encontrar la raíz cuadrada de números negativos". Finalmente, después de manejar la excepción, imprime "Después de la Excepción", demostrando que el flujo del programa continúa normalmente después de la captura y manejo de la excepción.

Algunas de las Principales excepciones en Julia son:

- __ErrorException__: La excepción genérica para errores.
- __ArgumentError__: Indica que un argumento pasado a una función es inválido.
- __DivideError__: Se lanza cuando se intenta dividir por cero.
- __BoundsError__: Se lanza cuando se intenta acceder a un índice fuera del rango de un array.
- __TypeError__: Indica que el tipo de un argumento es incorrecto.
- __MethodError__: Se lanza cuando no se encuentra un método adecuado para una llamada de función.
- __KeyError__: Indica que una clave no se encuentra en una colección.

Un ejemplo completo podría ser:



In [80]:
# Definición de una función que lanza varias excepciones
function calcular(a, b, c)
    try
        if b == 0
            throw(DivideError("No se puede dividir por cero"))
        end
        if c > length(a)
            throw(BoundsError("Índice fuera de rango"))
        end
        resultado = a[c] / b
        return resultado
    catch e
        if isa(e, DivideError)
            println("Error de división: ", e)
        elseif isa(e, BoundsError)
            println("Error de índice: ", e)
        else
            println("Otro error: ", e)
        end
    end
end

# Uso de la función con manejo de excepciones
a = [1, 2, 3]
calcular(a, 0, 2)  # Esto lanza un DivideError
calcular(a, 2, 4)  # Esto lanza un BoundsError
calcular(a, 2, 2)  # Esto funciona correctamente


Otro error: MethodError(DivideError, ("No se puede dividir por cero",), 0x0000000000007412)
Error de índice: BoundsError("Índice fuera de rango", #undef)


1.0